/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionInmueble.vista;

import GestionInmueble.controlador.ControlInmueble;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class DetallesInmueble extends javax.swing.JFrame {
    ControlInmueble ci;

    String columnas[] = {"id", "nombre", "apellido"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form DetallesInmueble
     */
    public DetallesInmueble() {
        initComponents();
        ci = new ControlInmueble();
        ci.setDetallesInmueble(this);
        ci.listadoAgentesInmueble();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgr_tipoProceso = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_descripcion = new javax.swing.JLabel();
        lbl_tipoInmueble = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_descripcion = new javax.swing.JTextArea();
        cbx_tipoInmueble = new javax.swing.JComboBox<>();
        lbl_registroInmueble = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        lbl_area = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbe_agenteEncargado = new javax.swing.JTable();
        txt_area = new javax.swing.JTextField();
        lbl_areaMetros = new javax.swing.JLabel();
        lbl_cantidadHabitaciones = new javax.swing.JLabel();
        dc_fechaVenta = new com.toedter.calendar.JDateChooser();
        txt_cantidadHabitaciones = new javax.swing.JTextField();
        lbl_cantidadBaños = new javax.swing.JLabel();
        txt_cantidadBaños = new javax.swing.JTextField();
        lbl_nPisos = new javax.swing.JLabel();
        txt_nPisos = new javax.swing.JTextField();
        lbl_direccion = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        lbl_precio = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        lbl_tipoProceso = new javax.swing.JLabel();
        rdb_venta = new javax.swing.JRadioButton();
        rdb_alquiler = new javax.swing.JRadioButton();
        lbl_fecha = new javax.swing.JLabel();
        lbl_agenteEncargado = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_estado = new javax.swing.JLabel();
        cbx_estado = new javax.swing.JComboBox<>();
        txt_agenteEncargado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_descripcion.setText("Descripción");

        lbl_tipoInmueble.setText("Tipo de inmueble:");

        txta_descripcion.setColumns(20);
        txta_descripcion.setRows(5);
        jScrollPane1.setViewportView(txta_descripcion);

        cbx_tipoInmueble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa", "Finca", "Local", "Lote" }));

        lbl_registroInmueble.setText("Registro Inmueble");

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        lbl_area.setText("Área:");

        tbe_agenteEncargado.setModel(modelo);
        jScrollPane3.setViewportView(tbe_agenteEncargado);

        lbl_areaMetros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_areaMetros.setText("m²");

        lbl_cantidadHabitaciones.setText("Cantidad de habitaciones:");

        lbl_cantidadBaños.setText("Cantidad de baños:");

        lbl_nPisos.setText("Nímero de pisos:");

        lbl_direccion.setText("Dirección:");

        lbl_precio.setText("Precio:");

        lbl_tipoProceso.setText("Tipo de proceso:");

        bgr_tipoProceso.add(rdb_venta);
        rdb_venta.setText("Venta");

        bgr_tipoProceso.add(rdb_alquiler);
        rdb_alquiler.setText("Alquiler");

        lbl_fecha.setText("Fecha:");

        lbl_agenteEncargado.setText("Agente encargado:");

        lbl_id.setText("id:");

        txt_id.setEditable(false);

        lbl_estado.setText("Estado:");

        cbx_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "En proceso", "Eliminado", "Terminado" }));

        txt_agenteEncargado.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(lbl_registroInmueble))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(btn_aceptar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(lbl_direccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lbl_precio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lbl_tipoInmueble)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbx_tipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lbl_area)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_areaMetros)
                                .addGap(32, 32, 32)
                                .addComponent(lbl_cantidadHabitaciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_cantidadHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(lbl_cantidadBaños)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cantidadBaños, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_nPisos)
                                    .addComponent(lbl_fecha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nPisos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dc_fechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_agenteEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_agenteEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_tipoProceso)
                                .addGap(18, 18, 18)
                                .addComponent(rdb_venta)
                                .addGap(18, 18, 18)
                                .addComponent(rdb_alquiler)
                                .addGap(32, 32, 32)
                                .addComponent(lbl_estado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbx_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                                .addComponent(lbl_descripcion)
                                .addGap(165, 165, 165))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_registroInmueble)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_tipoInmueble)
                        .addComponent(cbx_tipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_area)
                        .addComponent(txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_areaMetros))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_cantidadBaños)
                        .addComponent(txt_cantidadBaños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_cantidadHabitaciones)
                        .addComponent(txt_cantidadHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_nPisos)
                        .addComponent(txt_nPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_direccion)
                        .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_precio)
                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_id)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_tipoProceso)
                        .addComponent(rdb_venta)
                        .addComponent(rdb_alquiler)
                        .addComponent(lbl_estado)
                        .addComponent(cbx_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fecha)
                            .addComponent(dc_fechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_agenteEncargado)
                    .addComponent(lbl_descripcion)
                    .addComponent(txt_agenteEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_aceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        ci.actualizarInmueble();
        this.dispose();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    public void setTipoInmueble(String i) {
        cbx_tipoInmueble.setSelectedItem(i);
    }

    public void setArea(String area) {
        txt_area.setText(area);
    }

    public void setCantidadHabitaciones(String i) {
        txt_cantidadHabitaciones.setText(i);
    }

    public void setCantidadBaños(String i) {
        txt_cantidadBaños.setText(i);
    }

    public void setNPisos(String i) {
        txt_nPisos.setText(i);
    }

    public void setDireccion(String i) {
        txt_direccion.setText(i);
    }

    public void setPrecio(String i) {
        txt_precio.setText(i);
    }

    public void setId(String i) {
        txt_id.setText(i);
    }

    public void setTipoProceso(String i) {
        if (i.equals("Venta")) {
            this.rdb_venta.setSelected(true);
        }
        if (i.equals("Alquiler")) {
            this.rdb_alquiler.setSelected(true);
        }
    }

    public void setDescripcion(String i) {
        txta_descripcion.setText(i);
    }

    public void setFechaVenta(String i) {
        try {
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            Date fecha = formato.parse(i);
            dc_fechaVenta.setDate(fecha);
        } catch (ParseException ex) {

        }
    }

    public void setEstado(String i) {
        cbx_estado.setSelectedItem(i);
    }

    public void setAgenteEncargadoNombre(String i) {
        for (int j = 0; j < tbe_agenteEncargado.getRowCount(); j++) {
            if (tbe_agenteEncargado.getValueAt(j, 0).toString().equals(i)) {
                txt_agenteEncargado.setText(tbe_agenteEncargado.getValueAt(j, 1).toString() + " " + tbe_agenteEncargado.getValueAt(j, 2).toString());
            }
        }
    }

    public void setAgenteEncargado(String i) {
        for (int j = 0; j < tbe_agenteEncargado.getRowCount(); j++) {
            if (tbe_agenteEncargado.getValueAt(j, 0).toString().equals(i)) {
                tbe_agenteEncargado.getSelectionModel().setSelectionInterval(j, j);
            }
        }
    }

    public String getTipoInmueble() {
        return cbx_tipoInmueble.getSelectedItem().toString();
    }

    public double getArea() {
        return Double.parseDouble(txt_area.getText());
    }

    public int getCantidadHabitaciones() {
        return Integer.parseInt(txt_cantidadHabitaciones.getText());
    }

    public int getCantidadBaños() {
        return Integer.parseInt(txt_cantidadBaños.getText());
    }

    public int getNPisos() {
        return Integer.parseInt(txt_nPisos.getText());
    }

    public String getDireccion() {
        return txt_direccion.getText();
    }

    public double getPrecio() {
        return Double.parseDouble(txt_precio.getText());
    }

    public int getId() {
        return Integer.parseInt(txt_id.getText());
    }

    public String getTipoProceso() {
        if (rdb_alquiler.isSelected()) {
            return rdb_alquiler.getText();
        } else {
            return rdb_venta.getText();
        }
    }

    public String getDescripcion() {
        return txta_descripcion.getText();
    }

    public String getFechaVenta() {
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String date = formato.format(dc_fechaVenta.getDate());
        return date;
    }

    public String getEstado() {
        return String.valueOf(cbx_estado.getSelectedItem());
    }

    public long getAgenteEncargado() {
        return Long.parseLong(modelo.getValueAt(tbe_agenteEncargado.getSelectedRow(), 0).toString());
    }

    public void setModelo(DefaultTableModel modelo) {
        this.modelo = modelo;
    }

    public DefaultTableModel getModelo() {
        return modelo;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgr_tipoProceso;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JComboBox<String> cbx_estado;
    private javax.swing.JComboBox<String> cbx_tipoInmueble;
    private com.toedter.calendar.JDateChooser dc_fechaVenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_agenteEncargado;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_areaMetros;
    private javax.swing.JLabel lbl_cantidadBaños;
    private javax.swing.JLabel lbl_cantidadHabitaciones;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nPisos;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_registroInmueble;
    private javax.swing.JLabel lbl_tipoInmueble;
    private javax.swing.JLabel lbl_tipoProceso;
    private javax.swing.JRadioButton rdb_alquiler;
    private javax.swing.JRadioButton rdb_venta;
    private javax.swing.JTable tbe_agenteEncargado;
    private javax.swing.JTextField txt_agenteEncargado;
    private javax.swing.JTextField txt_area;
    private javax.swing.JTextField txt_cantidadBaños;
    private javax.swing.JTextField txt_cantidadHabitaciones;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nPisos;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextArea txta_descripcion;
    // End of variables declaration//GEN-END:variables
}
