/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionInmueble.vista;

import GestionCita.vista.Registro_cita;
import GestionInmueble.controlador.ControlInmueble;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Acer
 */
public class Listado_inmueble extends javax.swing.JPanel {

    ControlInmueble ci;

    String columnas[] = {"Id", "Tipo Inmueble", "Pisos", "Cantidad de habitaciones", "Precio", "Estado"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form Listado
     */
    public Listado_inmueble() {
        initComponents();
        ci = new ControlInmueble();
        ci.setListado(this);
        ci.listadoInmuebles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbe_listaInmuebles = new javax.swing.JTable();
        lbl_listadoInmuebles = new javax.swing.JLabel();
        btn_detalles = new javax.swing.JButton();
        lbl_buscar = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_cita = new javax.swing.JButton();
        cbx_filtro = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbe_listaInmuebles.setModel(modelo);
        jScrollPane1.setViewportView(tbe_listaInmuebles);

        lbl_listadoInmuebles.setText("Listado de Inmuebles");

        btn_detalles.setText("Detalles");
        btn_detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detallesActionPerformed(evt);
            }
        });

        lbl_buscar.setText("Buscar:");

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        btn_cita.setText("Cita");
        btn_cita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_citaActionPerformed(evt);
            }
        });

        cbx_filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Tipo Inmueble", "Pisos", "Cantidad de habitaciones", "Precio", "Estado" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(lbl_listadoInmuebles))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_buscar)
                                .addGap(18, 18, 18)
                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbx_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_detalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_cita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_listadoInmuebles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_buscar)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btn_detalles)
                        .addGap(38, 38, 38)
                        .addComponent(btn_cita))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_detallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detallesActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(this, "¿Desea ver los detalles de este inmueble?") == JOptionPane.YES_OPTION) {
                int id;
                id = Integer.parseInt(modelo.getValueAt(tbe_listaInmuebles.getSelectedRow(), 0).toString());
                ci.consultarInmuebleId(id);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar primero un inmueble");
        }
    }//GEN-LAST:event_btn_detallesActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        TableRowSorter<DefaultTableModel> Sorter;
        Sorter = new TableRowSorter<>(modelo);
        tbe_listaInmuebles.setRowSorter(Sorter);
        Sorter.setRowFilter(RowFilter.regexFilter(txt_buscar.getText(), cbx_filtro.getSelectedIndex()));
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void btn_citaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_citaActionPerformed
        Registro_cita AG = new Registro_cita();
        AG.setVisible(true);
        AG.setIdInmueble(modelo.getValueAt(tbe_listaInmuebles.getSelectedRow(), 0).toString());
        AG.setLocationRelativeTo(this);
    }//GEN-LAST:event_btn_citaActionPerformed

    public void setModelo(DefaultTableModel modelo) {
        this.modelo = modelo;
    }

    public DefaultTableModel getModelo() {
        return modelo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cita;
    private javax.swing.JButton btn_detalles;
    private javax.swing.JComboBox<String> cbx_filtro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_buscar;
    private javax.swing.JLabel lbl_listadoInmuebles;
    private javax.swing.JTable tbe_listaInmuebles;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
