/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionInmueble.vista;

import GestionInmueble.controlador.ControlInmueble;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class Registro_inmueble extends javax.swing.JPanel {

    String columnas[] = {"identificacion", "nombre", "apellido"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form Registro
     */
    public Registro_inmueble() {
        initComponents();
        ControlInmueble ci = new ControlInmueble();
        ci.setRegistro(this);
        ci.listadoAgentesRegistro();
    }
    
    public String fechaActual() {
        
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYYY");
        
        return formatoFecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_tipoProceso = new javax.swing.ButtonGroup();
        lbl_tipoInmueble = new javax.swing.JLabel();
        cbx_tipoInmueble = new javax.swing.JComboBox<>();
        lbl_registroInmueble = new javax.swing.JLabel();
        lbl_area = new javax.swing.JLabel();
        txt_area = new javax.swing.JTextField();
        lbl_areaMetros = new javax.swing.JLabel();
        lbl_cantidadHabitaciones = new javax.swing.JLabel();
        txt_cantidadHabitaciones = new javax.swing.JTextField();
        lbl_cantidadBaños = new javax.swing.JLabel();
        txt_cantidadBaños = new javax.swing.JTextField();
        lbl_nPisos = new javax.swing.JLabel();
        txt_nPisos = new javax.swing.JTextField();
        lbl_direccion = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        lbl_precio = new javax.swing.JLabel();
        txt_precio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rdb_venta = new javax.swing.JRadioButton();
        rdb_alquiler = new javax.swing.JRadioButton();
        lbl_fecha = new javax.swing.JLabel();
        lbl_agenteEncargado = new javax.swing.JLabel();
        lbl_descripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_descripcion = new javax.swing.JTextArea();
        btn_aceptar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbe_agenteEncargado = new javax.swing.JTable();
        dc_fechaVenta = new com.toedter.calendar.JDateChooser();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_tipoInmueble.setText("Tipo de inmueble:");

        cbx_tipoInmueble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa", "Finca", "Local", "Lote" }));

        lbl_registroInmueble.setText("Registro Inmueble");

        lbl_area.setText("Área:");

        lbl_areaMetros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_areaMetros.setText("m²");

        lbl_cantidadHabitaciones.setText("Cantidad de habitaciones:");

        lbl_cantidadBaños.setText("Cantidad de baños:");

        lbl_nPisos.setText("Nímero de pisos:");

        lbl_direccion.setText("Dirección:");

        lbl_precio.setText("Precio:");

        jLabel1.setText("Tipo de proceso:");

        btn_tipoProceso.add(rdb_venta);
        rdb_venta.setText("Venta");

        btn_tipoProceso.add(rdb_alquiler);
        rdb_alquiler.setText("Alquiler");

        lbl_fecha.setText("Fecha:");

        lbl_agenteEncargado.setText("Agente encargado:");

        lbl_descripcion.setText("Descripción");

        txta_descripcion.setColumns(20);
        txta_descripcion.setRows(5);
        jScrollPane1.setViewportView(txta_descripcion);

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        tbe_agenteEncargado.setModel(modelo);
        jScrollPane3.setViewportView(tbe_agenteEncargado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(lbl_registroInmueble))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lbl_nPisos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nPisos, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lbl_direccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(lbl_precio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl_tipoInmueble)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx_tipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_area)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_areaMetros)
                        .addGap(32, 32, 32)
                        .addComponent(lbl_cantidadHabitaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cantidadHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lbl_cantidadBaños)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cantidadBaños, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(btn_aceptar)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lbl_fecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dc_fechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(lbl_agenteEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdb_venta)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rdb_alquiler))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_descripcion)
                        .addGap(165, 165, 165))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_registroInmueble)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_tipoInmueble)
                        .addComponent(cbx_tipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_area)
                        .addComponent(txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_areaMetros))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_cantidadBaños)
                        .addComponent(txt_cantidadBaños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_cantidadHabitaciones)
                        .addComponent(txt_cantidadHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_nPisos)
                        .addComponent(txt_nPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_direccion)
                        .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_precio)
                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(rdb_venta)
                        .addComponent(rdb_alquiler))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fecha)
                            .addComponent(dc_fechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_agenteEncargado)
                    .addComponent(lbl_descripcion))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_aceptar)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        ControlInmueble ci = new ControlInmueble();
        ci.setRegistro(this);
        ci.registro();
    }//GEN-LAST:event_btn_aceptarActionPerformed
    
    public String getTipoInmueble() {
        return cbx_tipoInmueble.getSelectedItem().toString();
    }
    
    public double getArea() {
        return Double.parseDouble(txt_area.getText());
    }
    
    public int getCantidadHabitaciones() {
        return Integer.parseInt(txt_cantidadHabitaciones.getText());
    }
    
    public int getCantidadBaños() {
        return Integer.parseInt(txt_cantidadBaños.getText());
    }
    
    public int getNPisos() {
        return Integer.parseInt(txt_nPisos.getText());
    }
    
    public String getDireccion() {
        return txt_direccion.getText();
    }
    
    public double getPrecio() {
        return Double.parseDouble(txt_precio.getText());
    }
    
    public String getTipoProceso() {
        if (rdb_alquiler.isSelected()) {
            return rdb_alquiler.getText();
        } else {
            return rdb_venta.getText();
        }
    }
    
    public String getDescripcion() {
        return txta_descripcion.getText();
    }
    
    public String getFechaVenta(){
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        String date = formato.format(dc_fechaVenta.getDate());
        return date;
    }
    
    public long getAgenteEncargado(){
        return Long.parseLong(modelo.getValueAt(tbe_agenteEncargado.getSelectedRow(), 0).toString());
    } 
    
    public void setModelo(DefaultTableModel modelo) {
        this.modelo = modelo;
    }
    
    public DefaultTableModel getModelo() {
        return modelo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.ButtonGroup btn_tipoProceso;
    private javax.swing.JComboBox<String> cbx_tipoInmueble;
    private com.toedter.calendar.JDateChooser dc_fechaVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_agenteEncargado;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_areaMetros;
    private javax.swing.JLabel lbl_cantidadBaños;
    private javax.swing.JLabel lbl_cantidadHabitaciones;
    private javax.swing.JLabel lbl_descripcion;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_nPisos;
    private javax.swing.JLabel lbl_precio;
    private javax.swing.JLabel lbl_registroInmueble;
    private javax.swing.JLabel lbl_tipoInmueble;
    private javax.swing.JRadioButton rdb_alquiler;
    private javax.swing.JRadioButton rdb_venta;
    private javax.swing.JTable tbe_agenteEncargado;
    private javax.swing.JTextField txt_area;
    private javax.swing.JTextField txt_cantidadBaños;
    private javax.swing.JTextField txt_cantidadHabitaciones;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nPisos;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextArea txta_descripcion;
    // End of variables declaration//GEN-END:variables
}
