/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inmobiliariamonogatari;

import GestionCita.vista.Listado_cita;
import GestionInmueble.vista.Listado_inmueble;
import GestionUsuario.controlador.ControlUsuario;
import GestionInmueble.vista.Registro_inmueble;
import GestionUsuario.vista.Listado_usuario;
import GestionUsuario.vista.Registro_usuario;
import GestionUsuario.vista.Sesion;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_contenedor = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        lbl_usuarioSesion = new javax.swing.JLabel();
        menu_barra = new javax.swing.JMenuBar();
        menu_inmobiliaria = new javax.swing.JMenu();
        menu_iniciarSesion = new javax.swing.JMenuItem();
        menu_cerrarSesion = new javax.swing.JMenuItem();
        menu_usuarios = new javax.swing.JMenu();
        menu_registrarUsuario = new javax.swing.JMenuItem();
        menu_listadoUsuario = new javax.swing.JMenuItem();
        menu_inmuebles = new javax.swing.JMenu();
        menu_registrarInmuebles = new javax.swing.JMenuItem();
        menu_listadoInmueble = new javax.swing.JMenuItem();
        menu_citas = new javax.swing.JMenu();
        menu_citasAgendadas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p_contenedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout p_contenedorLayout = new javax.swing.GroupLayout(p_contenedor);
        p_contenedor.setLayout(p_contenedorLayout);
        p_contenedorLayout.setHorizontalGroup(
            p_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
        );
        p_contenedorLayout.setVerticalGroup(
            p_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        lbl_usuario.setText("Usuario en sesion:");

        lbl_usuarioSesion.setText(" ");

        menu_barra.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menu_inmobiliaria.setText("Inicio");

        menu_iniciarSesion.setText("Iniciar Sesión");
        menu_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_iniciarSesionActionPerformed(evt);
            }
        });
        menu_inmobiliaria.add(menu_iniciarSesion);

        menu_cerrarSesion.setText("Cerrar Sesión");
        menu_cerrarSesion.setEnabled(false);
        menu_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cerrarSesionActionPerformed(evt);
            }
        });
        menu_inmobiliaria.add(menu_cerrarSesion);

        menu_barra.add(menu_inmobiliaria);

        menu_usuarios.setText("Usuario");
        menu_usuarios.setEnabled(false);

        menu_registrarUsuario.setText("Registro");
        menu_registrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_registrarUsuarioActionPerformed(evt);
            }
        });
        menu_usuarios.add(menu_registrarUsuario);

        menu_listadoUsuario.setText("Listado");
        menu_listadoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listadoUsuarioActionPerformed(evt);
            }
        });
        menu_usuarios.add(menu_listadoUsuario);

        menu_barra.add(menu_usuarios);

        menu_inmuebles.setText("Inmueble");
        menu_inmuebles.setEnabled(false);

        menu_registrarInmuebles.setText("Registro");
        menu_registrarInmuebles.setEnabled(false);
        menu_registrarInmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_registrarInmueblesActionPerformed(evt);
            }
        });
        menu_inmuebles.add(menu_registrarInmuebles);

        menu_listadoInmueble.setText("Listado");
        menu_listadoInmueble.setEnabled(false);
        menu_listadoInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listadoInmuebleActionPerformed(evt);
            }
        });
        menu_inmuebles.add(menu_listadoInmueble);

        menu_barra.add(menu_inmuebles);

        menu_citas.setText("Cita");

        menu_citasAgendadas.setText("Citas Agendadas");
        menu_citasAgendadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_citasAgendadasActionPerformed(evt);
            }
        });
        menu_citas.add(menu_citasAgendadas);

        menu_barra.add(menu_citas);

        setJMenuBar(menu_barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_usuarioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_usuario)
                    .addComponent(lbl_usuarioSesion))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        lbl_usuario.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_iniciarSesionActionPerformed
        this.p_contenedor.removeAll();
        this.p_contenedor.updateUI();
        Sesion sesion = new Sesion(this);
        sesion.setSize(365, 200);
        sesion.setLocation((this.getWidth() / 2) - 180, 115);
        this.p_contenedor.add(sesion);
        sesion.setVisible(true);
        this.p_contenedor.validate();
    }//GEN-LAST:event_menu_iniciarSesionActionPerformed

    private void menu_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cerrarSesionActionPerformed
        JOptionPane.showMessageDialog(this, "Sesion Cerrada");
        p_contenedor.removeAll();
        p_contenedor.updateUI();
        menu_iniciarSesion.setEnabled(true);
        menu_usuarios.setEnabled(false);
        menu_cerrarSesion.setEnabled(false);
        menu_inmuebles.setEnabled(false);
        menu_listadoInmueble.setEnabled(false);
        menu_registrarInmuebles.setEnabled(false);
        menu_usuarios.setEnabled(false);
        ControlUsuario.usuario = null;
        lbl_usuarioSesion.setText("");
    }//GEN-LAST:event_menu_cerrarSesionActionPerformed

    private void menu_registrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_registrarUsuarioActionPerformed
        p_contenedor.removeAll();
        p_contenedor.updateUI();
        Registro_usuario r = new Registro_usuario();
        r.setSize(520, 280);
        r.setLocation((this.getWidth() / 2) - 260, 100);
        p_contenedor.add(r);
        r.setVisible(true);
        p_contenedor.validate();
    }//GEN-LAST:event_menu_registrarUsuarioActionPerformed

    private void menu_listadoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listadoUsuarioActionPerformed
        p_contenedor.removeAll();
        p_contenedor.updateUI();
        Listado_usuario l = new Listado_usuario();
        l.setSize(765, 350);
        l.setLocation((this.getWidth() / 2) - 380, 100);
        p_contenedor.add(l);
        l.setVisible(true);
        p_contenedor.validate();
    }//GEN-LAST:event_menu_listadoUsuarioActionPerformed

    private void menu_registrarInmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_registrarInmueblesActionPerformed
        p_contenedor.removeAll();
        p_contenedor.updateUI();
        Registro_inmueble r = new Registro_inmueble();
        r.setSize(875, 450);
        r.setLocation((this.getWidth() / 2) - 438, 40);
        p_contenedor.add(r);
        r.setVisible(true);
        p_contenedor.validate();
    }//GEN-LAST:event_menu_registrarInmueblesActionPerformed

    private void menu_listadoInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listadoInmuebleActionPerformed
        p_contenedor.removeAll();
        p_contenedor.updateUI();
        Listado_inmueble l = new Listado_inmueble();
        l.setSize(790, 370);
        l.setLocation((this.getWidth() / 2) - 395, 40);
        p_contenedor.add(l);
        l.setVisible(true);
        p_contenedor.validate();
    }//GEN-LAST:event_menu_listadoInmuebleActionPerformed

    private void menu_citasAgendadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_citasAgendadasActionPerformed
        p_contenedor.removeAll();
        p_contenedor.updateUI();
        Listado_cita g = new Listado_cita();
        g.setSize(835, 255);
        g.setLocation((this.getWidth() / 2) - 417, 125);
        p_contenedor.add(g);
        g.setVisible(true);
        p_contenedor.validate();

    }//GEN-LAST:event_menu_citasAgendadasActionPerformed

    public void mostrarUsuario() {
        lbl_usuarioSesion.setText(ControlUsuario.usuario.getNombre() + " " + ControlUsuario.usuario.getApellido());
//        r = new Reloj(this);
//        r.start();
    }

    public void activarCliente() {
        menu_iniciarSesion.setEnabled(false);
        menu_cerrarSesion.setEnabled(true);
        menu_inmuebles.setEnabled(true);
        p_contenedor.removeAll();
        p_contenedor.updateUI();
    }

    public void activarAgente() {
        menu_iniciarSesion.setEnabled(false);
        menu_cerrarSesion.setEnabled(true);
        menu_inmuebles.setEnabled(true);
        menu_listadoInmueble.setEnabled(true);
        menu_registrarInmuebles.setEnabled(true);
        p_contenedor.removeAll();
        p_contenedor.updateUI();
    }

    public void activarAdministrador() {
        menu_iniciarSesion.setEnabled(false);
        menu_cerrarSesion.setEnabled(true);
        menu_inmuebles.setEnabled(true);
        menu_listadoInmueble.setEnabled(true);
        menu_registrarInmuebles.setEnabled(true);
        menu_usuarios.setEnabled(true);
        p_contenedor.removeAll();
        p_contenedor.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JLabel lbl_usuarioSesion;
    private javax.swing.JMenuBar menu_barra;
    private javax.swing.JMenuItem menu_cerrarSesion;
    private javax.swing.JMenu menu_citas;
    private javax.swing.JMenuItem menu_citasAgendadas;
    private javax.swing.JMenuItem menu_iniciarSesion;
    private javax.swing.JMenu menu_inmobiliaria;
    private javax.swing.JMenu menu_inmuebles;
    private javax.swing.JMenuItem menu_listadoInmueble;
    private javax.swing.JMenuItem menu_listadoUsuario;
    private javax.swing.JMenuItem menu_registrarInmuebles;
    private javax.swing.JMenuItem menu_registrarUsuario;
    private javax.swing.JMenu menu_usuarios;
    private javax.swing.JPanel p_contenedor;
    // End of variables declaration//GEN-END:variables
}
