/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionUsuario.vista;

import GestionUsuario.controlador.ControlUsuario;
import inmobiliariamonogatari.Ventana;

/**
 *
 * @author Acer
 */
public class Sesion extends javax.swing.JPanel {

    /**
     * Creates new form Sesion
     */
    
    public Ventana v;
    
    public Sesion(Ventana v) {
        this.v = v;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_iniciarSesion = new javax.swing.JLabel();
        lbl_identificacionSesion = new javax.swing.JLabel();
        txt_identificacionSesion = new javax.swing.JTextField();
        lbl_contraseñaSesion = new javax.swing.JLabel();
        btn_aceptarSesion = new javax.swing.JButton();
        psw_contraseñaSesion = new javax.swing.JPasswordField();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_iniciarSesion.setText("Iniciar Sesion");

        lbl_identificacionSesion.setText("Identificación:");

        lbl_contraseñaSesion.setText("Contraseña:");

        btn_aceptarSesion.setText("Aceptar");
        btn_aceptarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_identificacionSesion)
                            .addComponent(lbl_contraseñaSesion))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_identificacionSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(psw_contraseñaSesion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(lbl_iniciarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btn_aceptarSesion)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_iniciarSesion)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_identificacionSesion)
                    .addComponent(txt_identificacionSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_contraseñaSesion)
                    .addComponent(psw_contraseñaSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_aceptarSesion)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarSesionActionPerformed
        ControlUsuario cu = new ControlUsuario();
        cu.setSesion(this);
        cu.iniciarSesion();
    }//GEN-LAST:event_btn_aceptarSesionActionPerformed
    
    public void activarCliente(){
        v.activarCliente();
    }
    
    public void activarAdministrador(){
        v.activarAdministrador();
    }
    
    public void activarAgente(){
        v.activarAgente();
    }
    
    public void setIdentificacion(String i){
        txt_identificacionSesion.setText(i);
    }
    
    public void setContraseña(String c){
        psw_contraseñaSesion.setText(c);
    }
    
    public String getIdentificacion(){
        return txt_identificacionSesion.getText();
    }
    
    public String getContraseña(){
        return String.valueOf(psw_contraseñaSesion.getPassword());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptarSesion;
    private javax.swing.JLabel lbl_contraseñaSesion;
    private javax.swing.JLabel lbl_identificacionSesion;
    private javax.swing.JLabel lbl_iniciarSesion;
    private javax.swing.JPasswordField psw_contraseñaSesion;
    private javax.swing.JTextField txt_identificacionSesion;
    // End of variables declaration//GEN-END:variables
}
